<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Grammar-Quiz | Hope English Language Center</title>
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="assets/css/style.css" />
  </head>

  <body>
    <nav class="fixed-timer">
      <!-- logo  -->
      <a href="index.php" class="logo" id="desktop-logo">
        <div class="logo-icon">H</div>
        <div class="logo-text">
          <div class="brand-name">Hope English</div>
          <div class="tagline">Language Center</div>
        </div>
      </a>
      <div class="timer-content">
        <div class="timer-text">Time Remaining:</div>
        <div id="time">3:00</div>
      </div>
    </nav>
    <div class="scroll-progress" id="scrollProgress"></div>
    <div class="wrapper">
      <section id="quiz-sect">
        <!-- Main Content -->
        <div class="container">
          <!-- Header -->
          <div class="header">
            <h1 class="quiz-title">Present Simple Tense</h1>
            <p class="quiz-description">
              Choose the correct option to test yourself.
            </p>
            <!-- Student Info -->
            <div class="student-info">
              <div class="info-card">
                <h3>
                  <i class="ri-user-line"></i>Name: <span>Muhammad Umer</span>
                </h3>
                <!-- <p id="student-name">
                <?php echo htmlspecialchars($student_name); ?>
                 Muhammad Umer
              </p> -->
              </div>
              <div class="info-card">
                <h3>
                  <i class="ri-list-ordered-2"></i> Total Questions:
                  <span>10</span>
                </h3>
                <!-- <p id="total-questions">10</p> -->
              </div>
              <div class="info-card">
                <h3>
                  <i class="ri-hourglass-fill"></i> Duration:
                  <span>3 Minutes</span>
                </h3>
                <!-- <p>3 Minutes</p> -->
              </div>
            </div>
          </div>

          <!-- Questions Container -->
          <form
            action="submit.php"
            method="post"
            id="quiz-form"
            class="questions-container"
          >
            <input
              type="hidden"
              name="test_id"
              value="<?php echo htmlspecialchars($test_id); ?>"
            />
            <input
              type="hidden"
              name="student_id"
              value="<?php echo htmlspecialchars($student_id); ?>"
            />

            <h2 class="section-title">
              <i class="ri-question-fill"></i> Questions
            </h2>

            <?php
      // This section would be generated by your PHP code
      // I'm creating 3 sample questions to show the design
      ?>

            <!-- Question 1 -->
            <div class="question">
              <!-- <span class="question-number">1</span> -->
              <div class="question-text">
                Which word is the correct translation for "book" in Spanish?
              </div>

              <div class="options">
                <div class="two-options">
                  <div class="option">
                    <input
                      type="radio"
                      id="q1_opt1"
                      name="ans[1]"
                      value="1"
                      required
                    />
                    <label for="q1_opt1" class="option-label">
                      <span class="option-text">Libro</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q1_opt2" name="ans[1]" value="2" />
                    <label for="q1_opt2" class="option-label">
                      <span class="option-text">Casa</span>
                    </label>
                  </div>
                </div>
                <div class="two-options">
                  <div class="option">
                    <input type="radio" id="q1_opt3" name="ans[1]" value="3" />
                    <label for="q1_opt3" class="option-label">
                      <span class="option-text">Mesa</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q1_opt4" name="ans[1]" value="4" />
                    <label for="q1_opt4" class="option-label">
                      <span class="option-text">Pluma</span>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <!-- Question 2 -->
            <div class="question">
              <!-- <span class="question-number">2</span> -->
              <div class="question-text">
                What is the feminine form of "un amigo" (a friend) in French?
              </div>

              <div class="options">
                <div class="two-options">
                  <div class="option">
                    <input
                      type="radio"
                      id="q2_opt1"
                      name="ans[2]"
                      value="5"
                      required
                    />
                    <label for="q2_opt1" class="option-label">
                      <span class="option-text">Une amie</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q2_opt2" name="ans[2]" value="6" />
                    <label for="q2_opt2" class="option-label">
                      <span class="option-text">Un ami</span>
                    </label>
                  </div>
                </div>

                <div class="two-options">
                  <div class="option">
                    <input type="radio" id="q2_opt3" name="ans[2]" value="7" />
                    <label for="q2_opt3" class="option-label">
                      <span class="option-text">Une amigue</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q2_opt4" name="ans[2]" value="8" />
                    <label for="q2_opt4" class="option-label">
                      <span class="option-text">Un amie</span>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <!-- Question 3 -->
            <div class="question">
              <!-- <span class="question-number">3</span> -->
              <div class="question-text">
                Which of these is NOT a correct German article for a masculine
                noun?
              </div>

              <div class="options">
                <div class="two-options">
                  <div class="option">
                    <input
                      type="radio"
                      id="q3_opt1"
                      name="ans[3]"
                      value="9"
                      required
                    />
                    <label for="q3_opt1" class="option-label">
                      <span class="option-text">Der</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q3_opt2" name="ans[3]" value="10" />
                    <label for="q3_opt2" class="option-label">
                      <span class="option-text">Die</span>
                    </label>
                  </div>
                </div>
                <div class="two-options">
                  <div class="option">
                    <input type="radio" id="q3_opt3" name="ans[3]" value="11" />
                    <label for="q3_opt3" class="option-label">
                      <span class="option-text">Das</span>
                    </label>
                  </div>

                  <div class="option">
                    <input type="radio" id="q3_opt4" name="ans[3]" value="12" />
                    <label for="q3_opt4" class="option-label">
                      <span class="option-text">Den</span>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <!-- More questions would be generated by PHP here -->
          </form>
          <!-- Submit Button -->
          <div class="submit-section">
            <button
              type="submit"
              form="quiz-form"
              class="cta-button submit-btn"
            >
              <i class="ri-send-plane-fill"></i> Submit Quiz
            </button>
          </div>
        </div>

        <!-- Footer -->
        <div class="footer">
          <p>© 2023 Language Center. All answers are final once submitted.</p>
        </div>
      </section>
    </div>
    <!-- <script>
    let totalTime = 3 * 60;
    const timerEl = document.getElementById("time");
    const form = document.getElementById("quiz-form");

    function startTimer() {
      let minutes = Math.floor(totalTime / 60);
      let seconds = totalTime % 60;

      timerEl.textContent =
        minutes + ":" + (seconds < 10 ? "0" : "") + seconds;

      if (totalTime <= 0) {
        alert("Time is up! Your quiz will be submitted automatically.");
        form.submit();
      }

      totalTime--;
    }

    // Start the timer
    setInterval(startTimer, 1000);

    // Initialize the timer display immediately
    startTimer();

    // Form submission confirmation
    form.addEventListener("submit", function (e) {
      // Check if all questions are answered (optional)
      const radioButtons = document.querySelectorAll(
        'input[type="radio"]:checked'
      );
      const totalQuestions = document.querySelectorAll(".question").length;

      if (radioButtons.length < totalQuestions) {
        e.preventDefault();
        const confirmSubmit = confirm(
          `You have answered ${radioButtons.length} out of ${totalQuestions} questions. Are you sure you want to submit?`
        );

        if (confirmSubmit) {
          form.submit();
        }
      }
    });

  </script> -->

    <script>
      const scrollProgress = document.getElementById("scrollProgress");
      const wrapper = document.querySelector(".wrapper");
      window.addEventListener("scroll", function () {
        const scrolled = window.scrollY;
        const rate = scrolled * -0.2;

        if (wrapper) {
          wrapper.style.transform = `translateY(${rate}px)`;
        }
      });
    </script>
  </body>
</html>
